apiVersion: v1
kind: Service
metadata:
  name: petclinic-app-service
spec:
  type: NodePort
  selector:
    app: petclinic-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31655